// Code generated by "stringer -type=color"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Black-0]
	_ = x[Blue-1]
	_ = x[Orange-2]
	_ = x[Red-3]
}

const _color_name = "BlackBlueOrangeRed"

var _color_index = [...]uint8{0, 5, 9, 15, 18}

func (i color) String() string {
	if i < 0 || i >= color(len(_color_index)-1) {
		return "color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _color_name[_color_index[i]:_color_index[i+1]]
}
