// Code generated by "stringer -type=setType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Run-0]
	_ = x[Group-1]
	_ = x[Invalid-2]
}

const _setType_name = "RunGroupInvalid"

var _setType_index = [...]uint8{0, 3, 8, 15}

func (i setType) String() string {
	if i < 0 || i >= setType(len(_setType_index)-1) {
		return "setType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _setType_name[_setType_index[i]:_setType_index[i+1]]
}
